name: CML & DVC
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Create CML report
        env:
          # AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          GDRIVE_ACCESS_DATA: ${{ secrets.GDRIVE_ACCESS_DATA }}
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        run: |
          # Your ML workflow goes here
          pip install -r requirements.txt
          # dvc remote modify filterout --local gdrive_user_credentials_file .dvc/tmp/gdrive-user-credentials.json
          dvc pull

          dvc repro

          git fetch --prune
          # dvc metrics diff --show-md main > report.md
          # cml-send-comment report.md